variable "eks-cluster" {}
variable "nodegroup-name" {}
#variable "instancetype" {}
#variable "ami-type" {}
variable "disk-size" {}
variable "node-role" {}
variable "subnet-ids" {}
variable "ami" {}
#variable "capacity-type" {}
variable "desiredsize" {}
variable "maxsize" {}
variable "minsize" {}
#variable "Application" {}
#variable "Description" {}
#variable "OpCo" {}
#variable "Ec2ctl" {}
#variable "Dtap" {}
#variable "Creator" {}
#variable "Owner" {}
variable "ltname" {}
variable "ltversion" {}
#variable "nodgrouptemplatename" {}
//variable "imageid" {}
//variable "security_gp_id" {}