variable "eks-cluster-name" {}
variable "cluster-role" {}
variable "enable-cluster-log" {}
variable "eks-version" {}
variable "subnet-ids" {}
variable "endpoint-private-access" {}
variable "endpoint-public-access" {}
variable "eks-service-cidr" {}
variable "eks-sg-name" {}
