variable "lt_name" {}
variable "ebs_optimized" {}
#variable "image_id" {}
variable "instance_type" {}
#variable "eks-sg-name" {}
#variable "security-gp-id" {}
variable "eks-cluster-name" {}
#variable "clustersg" {}
#variable "nodegroupname" {}
variable "region" {}
